apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: kafka-broker
          image: bitnami/kafka:latest   
          env:
            - name: KAFKA_KRAFT_MODE
              value: "true"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "PLAINTEXT"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/opt/kafka/data"
          volumeMounts:
            - name: kafka-config
              mountPath: /opt/kafka/config
            - name: kafka-data
              mountPath: /opt/kafka/data
      volumes:
        - name: kafka-config
          persistentVolumeClaim:
            claimName: kafka-config-pvc
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-broker
  ports:
    - name: plain
      protocol: TCP
      port: 9092
      targetPort: 9092
